const NODEMAILER_USER = process.env.NODEMAILER_USER
const NODEMAILER_PASS = process.env.NODEMAILER_PASS
const NODEMAILER_SECRET_KEY = process.env.NODEMAILER_SECRET_KEY

module.exports = {
	NODEMAILER_USER,
	NODEMAILER_PASS,
	NODEMAILER_SECRET_KEY
}